config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  devise_for :members
  resources :cribs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crib.rb
class Crib < ApplicationRecord
  mount_uploaders :pics, PicUploader
  belongs_to :member
  validates :title, presence: true, length: {minimum: 5, maximum: 200}
  validates :summary, presence: true, length: {minimum: 20, maximum: 1000}
  validates :rent, :room_type, :bath_type, :owner_type, :lease_type, :pets, :smoking, presence: true
  validates :availability, date: { after_or_equal_to: Proc.new { Date.today }, message: 'must be after today' }, on: :create
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :profile, ProfileUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cribs

  validates :username, presence: true, uniqueness: true, length: {minimum: 3, maximum: 30}
  validates :full_name, presence: true, length: {minimum: 3, maximum: 100}
  validates_presence_of :contact
  validates :dob, date: {before: Proc.new {Date.today}, message: 'must be before today'}, on: :create
  validates_presence_of   :profile
  validates_integrity_of  :profile
  validates_processing_of :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :full_name, :contact, :dob, :profession, :profile, :profile_cache, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/cribs_controller.rb
class CribsController < ApplicationController
  before_action :set_crib, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_member!, except: [:index]

  # GET /cribs
  # GET /cribs.json
  def index
    @cribs = Crib.all
  end

  # GET /cribs/1
  # GET /cribs/1.json
  def show
  end

  # GET /cribs/new
  def new
    @crib = current_member.cribs.build
  end

  # GET /cribs/1/edit
  def edit
  end

  # POST /cribs
  # POST /cribs.json
  def create
    @crib = current_member.cribs.build(crib_params)

    respond_to do |format|
      if @crib.save
        format.html { redirect_to @crib, notice: 'Crib was successfully created.' }
        format.json { render :show, status: :created, location: @crib }
      else
        format.html { render :new }
        format.json { render json: @crib.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cribs/1
  # PATCH/PUT /cribs/1.json
  def update
    respond_to do |format|
      if @crib.update(crib_params)
        format.html { redirect_to @crib, notice: 'Crib was successfully updated.' }
        format.json { render :show, status: :ok, location: @crib }
      else
        format.html { render :edit }
        format.json { render json: @crib.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cribs/1
  # DELETE /cribs/1.json
  def destroy
    @crib.destroy
    respond_to do |format|
      format.html { redirect_to cribs_url, notice: 'Crib was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crib
      @crib = Crib.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crib_params
      params.require(:crib).permit(:title, :summary, :rent, :availability, :room_type, :bath_type, :owner_type, :lease_type, :prefer_gender, :extras, :pets, :smoking,
                                   :washndry, :microwave, :heater, :wifi, :furnish, {pics: []})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carousel_helper.rb
# app/helpers/carousel_helper.rb

module CarouselHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: {
          target: uid,
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, image_tag(image), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

app/helpers/cribs_helper.rb
module CribsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cribs/_form.html.erb
<%= form_for(crib) do |f| %>
  <% if crib.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crib.errors.count, "error") %> prohibited this crib from being saved:</h2>

      <ul>
      <% crib.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Room Details</h3>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :summary %>
    <%= f.text_area :summary %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.number_field :rent %>
  </div>

  <div class="field">
    <%= f.label :availability %>
    <%= f.date_field :availability %>
  </div>

  <div class="field">
    <%= f.label :room %>
    <%= f.select :room_type, options_for_select(['Private', 'Shared', 'Paying Guest', 'Entire Home'], f.object.room_type) %>
  </div>

  <div class="field">
    <%= f.label :bath %>
    <%= f.select :bath_type, options_for_select(['Attached', 'Common'], f.object.bath_type) %>
  </div>

  <div class="field">
    <%= f.label :ownership %>
    <%= f.select :owner_type, options_for_select(['Rental', 'Owner', 'Agent']) %>
  </div>

  <div class="field">
    <%= f.label :lease_type, "Type of Lease" %>
    <%= f.select :lease_type, options_for_select([['Short (30days - 180days)','Short term'], ['Long (> 180days)', 'Long term']], f.object.lease_type) %>
  </div>

  <h3>Preferences</h3>

  <div class="field">
    <%= f.label :prefer_gender, "Preferred Gender" %>
    <%= f.select :prefer_gender, options_for_select(['Male', 'Female', 'Any'], f.object.prefer_gender) %>
  </div>

  <div class="field">
    <%= f.label :pets, "Pet Policy" %>
    <%= f.select :pets, options_for_select(['No Pets', 'Pets Ok'], f.object.pets) %>
  </div>

  <div class="field">
    <%= f.label :smoking, "Smoking Policy" %>
    <%= f.select :smoking, options_for_select(['No Smoking', 'Smoking Ok'], f.object.smoking) %>
  </div>

  <h3>Amenities</h3>
  <div class="field">
    <%= f.label :microwave, "Mircowave" %>
    <%= f.check_box :microwave %>
    <%= f.label :heater, "Heater" %>
    <%= f.check_box :heater %>
    <%= f.label :wifi, "Wi-Fi" %>
    <%= f.check_box :wifi %>
  </div>

  <div class="field">
    <%= f.label :washndry, "Washer & Dryer" %>
    <%= f.select :washndry, options_for_select([['In House', 'in apartment'],['Separate Laundry', 'in community'],['No Laundry', 'not available']], f.object.washndry) %>
  </div>

  <div class="field">
    <%= f.label :furnish, "Furnishing Details" %>
    <%= f.select :furnish, options_for_select(['Not Furnished', 'Partially Furnished', 'Furnished with bed', 'Fully Furnished'], f.object.furnish) %>
  </div>

  <div class="field">
    <%= f.label :extras, "Other Amenities" %>
    <%= f.text_area :extras %>
  </div>

  <div class="field">
    <%= f.label :pics, "Upload Property Pics" %>
    <%= f.file_field :pics, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cribs/edit.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit <%= @crib.title %>| UrCrib</title>
</head><!--/head-->


<div class="container">
  <div class="col-md-4">
    <h1>Editing Crib</h1>
    <%= render 'form', crib: @crib %>

    <%= link_to 'Cancel', cribs_path %> |
    <%= link_to 'Back', @crib %>
  </div>
</div>

app/views/cribs/index.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Find Cribs | UrCrib.com </title>
</head>

<body>
  <section id="page-breadcrumb">
      <div class="vertical-center sun">
           <div class="container">
              <div class="row">
                  <div class="action">
                      <div class="col-sm-12">
                          <h1 class="title">Search by Zip Code or City</h1>
                          <p>Search box details go here</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--/#page-breadcrumb-->

  <section id="projects">
      <div class="container">
          <div class="row">
            <ul class="portfolio-filter text-center">
                <li><h4 class="btn btn-default">Sort Options:</h4></li>
                <li><h4 class="btn"> Availability</h4></li>
                <li><h4 class="btn"> Posted Date</h4></li>
                <li><h4 class="btn"> Rent: Low to High </h4></li>
                <li><h4 class="btn"> Rent: High to Low </h4></li>
            </ul><!--/#portfolio-filter-->
              <div class="col-md-3 col-sm-4">
                  <div class="sidebar portfolio-sidebar">
                      <div class="sidebar-item categories">
                          <h3>Crib Search Filters</h3>
                          <ul class="nav navbar-stacked">
                              <li><a href="#">Location<span class="pull-right">(1)</span></a></li>
                              <li class="active"><a href="#">Rent Range<span class="pull-right">(8)</span></a></li>
                              <li><a href="#">Listed By<span class="pull-right">(4)</span></a></li>
                              <li><a href="#">Lease Type<span class="pull-right">(9)</span></a></li>
                              <li><a href="#">Room Type<span class="pull-right">(4)</span></a></li>
                              <li><a href="#">Bath Type<span class="pull-right">(3)</span></a></li>
                              <li><a href="#">Php<span class="pull-right">(2)</span></a></li>
                              <li><a href="#">Wordpress<span class="pull-right">(8)</span></a></li>
                          </ul>
                      </div>
                      <div class="sidebar-item  recent">
                          <h3>Recent Projects</h3>
                          <div class="media">
                              <div class="pull-left">
                                  <a href="#"><%= image_tag "temp/project1.jpg" %></a>
                              </div>
                              <div class="media-body">
                                  <h4><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit,</a></h4>
                                  <p>posted on  07 March 2014</p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="col-md-9 col-sm-8">
                  <div class="row">
                    <% @cribs.each do |crib| %>
                        <div class="col-xs-6 col-sm-6 col-md-4 blog-padding-right">
                           <div class="single-blog two-column">
                               <div class="post-thumb">
                                   <%= link_to image_tag(crib.pics[0].url(:thumb)), crib, class: "img-responsive"%>
                                   <div class="post-overlay">
                                       <span class="uppercase"><a href="#"><%= crib.availability.strftime('%d')%><br><small><%= crib.availability.strftime('%b')%></small></a></span>
                                   </div>
                               </div>
                               <div class="post-content overflow">
                                   <h2 class="post-title bold" style="text-align: justify;"><%= link_to crib.title, crib %></h2>
                                   <h3 class="post-author"><p>Posted by <%= crib.member.username %></p></h3>
                                   <div class="post-bottom overflow">
                                       <ul class="nav nav-justified post-nav">
                                           <li><p><i class="fa fa-usd"></i> <%= crib.rent %></p></li>
                                           <li><p><i class="fa fa-calendar"></i> <%= crib.availability.strftime('%d %b') %></p></li>
                                           <li><p class="text-center"><%= link_to "View Details", class: "btn btn-success", role: "button" %></p></li>
                                       </ul>
                                   </div>
                               </div>
                          </div>
                       </div>
                   <% end %>
                  </div>
              </div>
          </div>
      </div>
  </section>
</body>

app/views/cribs/new.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Crib Post | UrCrib</title>
</head>

<body>
  <div class="container">
    <div class="col-md-4">
      <h1>New Crib</h1>
      <%= render 'form', crib: @crib %>

      <%= link_to 'Back', cribs_path %>
    </div>
  </div>
</body>

app/views/cribs/show.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @crib.title %>| UrCrib</title>
</head>

<body>
  <section id="portfolio-information">
      <div class="container">
          <div class="row">
              <div class="col-md-6 text-center">
                <% image_urls = @crib.pics.map {|image| image.medium.url} %>
                <%= carousel_for(image_urls) %>
              </div>
              <div class="col-sm-6">
                  <div class="project-name overflow">
                      <h2 class="bold"><%= @crib.title %> </h2>
                      <ul class="nav navbar-nav navbar-default">
                          <li><a href="#"><i class="fa fa-clock-o"></i>Posted on <%= @crib.created_at.strftime('%m-%d-%y') %> by <%= @crib.member.username %></a></li>
                      </ul>
                  </div>
                  <div class="project-info overflow">
                      <p style="text-align: justify;"><br><%= @crib.summary %></p>
                      <div class="skills overflow">
                          <h3>Amenities:</h3>
                          <ul class="nav navbar-nav navbar-default">
                              <li>
                                <% if @crib.microwave %>
                                  <p><i class="fa fa-check-square"></i> Microwave &nbsp;</p>
                                <% else %>
                                  <p><i class="fa fa-square-o"></i> Microwave &nbsp;</p>
                                <% end %>
                              </li>
                              <li>
                                <% if @crib.heater %>
                                  <p><i class="fa fa-check-square"></i> Heater/AC &nbsp;</p>
                                <% else %>
                                  <p><i class="fa fa-square-o"></i> Heater/AC &nbsp;</p>
                                <% end %>
                              </li>
                              <li>
                                <% if @crib.wifi %>
                                  <p><i class="fa fa-check-square"></i> WiFi &nbsp;</p>
                                <% else %>
                                  <p><i class="fa fa-square-o"></i> WiFi &nbsp;</p>
                                <% end %>
                              </li>
                          </ul>
                      </div>
                      <ul class="elements">
                        <h3>Crib Details</h3>
                          <li><p><i class="fa fa-angle-right"></i> <%= @crib.room_type %> room with <%= @crib.bath_type %> Bathroom</p></li>
                          <li><p><i class="fa fa-angle-right"></i> Available for <%= @crib.lease_type %> lease (> 180days)</p></li>
                          <li><p><i class="fa fa-angle-right"></i> Preferences: <br> &nbsp; &nbsp; &nbsp; <span style="font-weight: 700;">Gender:</span> <%= @crib.prefer_gender %>, <span style="font-weight: 700;">Pets Policy:</span> <%= @crib.pets %>, <span style="font-weight: 700;">Smoking Policy:</span> <%= @crib.smoking %></p></li>
                          <li><p><i class="fa fa-angle-right"></i> Space is <%= @crib.furnish %> and Laundry <%= @crib.washndry %></p></li>
                          <li><p><i class="fa fa-angle-right"></i> Other Amenities: <%= @crib.extras %></p></li>
                      </ul>
                  </div>
                  <div class="client overflow">
                      <h3>Rent:</h3>
                      <ul class="nav navbar-nav navbar-default">
                          <li><p><i class="fa fa-usd"></i> <%= @crib.rent %>/month</p></li>
                      </ul>
                  </div>
                  <div class="live-preview">
                    <% if @crib.member == current_member %>
                      <%= link_to 'Edit', edit_crib_path(@crib), class: "btn btn-common uppercase" %>
                      <%= link_to 'Delete', crib_path(@crib), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-common uppercase" %>
                      <%= link_to 'Back', cribs_path, class: "btn btn-common uppercase" %>
                    <% else %>
                      <a href="#" class="btn btn-common uppercase">Message "<%= @crib.member.username %>"</a>
                    <% end %>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <br>
  <br>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!--[if lt IE 9]>
	    <script src="js/html5shiv.js"></script>
	    <script src="js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <header id="header">
        <div class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">

                    <a class="navbar-brand" href="/">
                    	<h1><%= image_tag "temp/logo12.png", style: "width: 200px;" %></h1>
                    </a>

                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/cribs">Find Cribs</a></li>
                        <li><a href="#">Moving Sales</a></li>
                        <li><a href="#">Contact</a></li>
                        <% if member_signed_in? %>
                          <li><%= link_to 'SIGN OUT', destroy_member_session_path, method: :delete %></li>
                        <% else %>
                          <li><a href="/members/sign_in">SIGN IN</a></li>
                        <% end %>
                    </ul>
                </div>
                <div class="search">
                    <form role="form">
                        <i class="fa fa-search"></i>
                        <div class="field-toggle">
                            <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center bottom-separator">
                    <%= image_tag "temp/under.png", class: "img-responsive inline" %>
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="testimonial bottom">
                        <h2>Popular Post</h2>
                        <div class="media">
                            <div class="pull-left">
                                <a href="#"><%= image_tag "temp/profile1.png" %></a>
                            </div>
                            <div class="media-body">
                                <blockquote>Nisi commodo bresaola, leberkas venison eiusmod bacon occaecat labore tail.</blockquote>
                                <h3><a href="#">- Jhon Kalis</a></h3>
                            </div>
                         </div>
                         <h2>Recent Post</h2>
                        <div class="media">
                            <div class="pull-left">
                                <a href="#"><%= image_tag "temp/profile2.png" %></a>
                            </div>
                            <div class="media-body">
                                <blockquote>Capicola nisi flank sed minim sunt aliqua rump pancetta leberkas venison eiusmod.</blockquote>
                                <h3><a href="">- Abraham Josef</a></h3>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="contact-info bottom">
                        <h2>Contacts</h2>
                        <address>
                        E-mail: <a href="mailto:support@urcrib.com">support@urcrib.com</a> <br>
                        Phone: +1 (123) 456 7890 <br>
                        Fax: +1 (123) 456 7891 <br>
                        </address>

                        <h2>Address</h2>
                        <address>
                        San Jose, CA <br>
                        United States <br>
                        </address>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12">
                    <div class="contact-form bottom">
                        <h2>Send a message</h2>
                        <form id="main-contact-form" name="contact-form" method="post" action="sendemail.php">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
                            </div>
                            <div class="form-group">
                                <input type="email" name="email" class="form-control" required="required" placeholder="Email Id">
                            </div>
                            <div class="form-group">
                                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your text here"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-submit" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="copyright-text text-center">
                        <p>&copy; Your Company 2014. All Rights Reserved.</p>
                        <p>Create by <a target="_blank" href="http://www.codevarma.com">Varma</a> &amp; <a target="_blank" href="#">Raja</a>. Designed by <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UrCrib | Welcome</title>
</head><!--/head-->

<body>
  <section id="home-slider">
      <div class="container">
          <div class="main-slider">
              <div class="slide-text">
                <h1>Find Ur Crib</h1>
                <p>Moving to a new place? Ur Crib can help you find the perfect location, Roommate, learn about your new neighborhood &amp; sell your items before moving.</p>
                <a href="/members/sign_up" class="btn btn-common">GET STARTED</a>
              </div>
              <%= image_tag "temp/house.png", class: "img-responsive slider-house", alt: "slider image" %>
              <%= image_tag "temp/circle1.png", class: "slider-circle1", alt: "slider image" %>
              <%= image_tag "temp/circle2.png", class: "slider-circle2", alt: "slider image" %>
              <%= image_tag "temp/cloud1.png", class: "slider-cloud1", alt: "slider image" %>
              <%= image_tag "temp/cloud2.png", class: "slider-cloud2", alt: "slider image" %>
              <%= image_tag "temp/cloud3.png", class: "slider-cloud3", alt: "slider image" %>
              <%= image_tag "temp/sun.png", class: "slider-sun", alt: "slider image" %>
              <%= image_tag "temp/cycle.png", class: "slider-cycle", alt: "slider image" %>
          </div>
      </div>
  </section>

  <section id="services">
      <div class="container">
          <div class="row">
              <div class="col-sm-4 text-center padding wow fadeIn" data-wow-duration="1000ms" data-wow-delay="300ms">
                  <div class="single-service">
                      <div class="wow scaleIn" data-wow-duration="500ms" data-wow-delay="300ms">
                          <%= image_tag "temp/icon1.png" %>
                      </div>
                      <h2>Find Good Locations</h2>
                      <p>Get to know the place before you move. See nearby transit, restaurants &amp; stores info to find the best crib suitable.</p>
                  </div>
              </div>
              <div class="col-sm-4 text-center padding wow fadeIn" data-wow-duration="1000ms" data-wow-delay="600ms">
                  <div class="single-service">
                      <div class="wow scaleIn" data-wow-duration="500ms" data-wow-delay="600ms">
                          <%= image_tag "temp/icon2.png" %>
                      </div>
                      <h2>Avoid Cold Feet</h2>
                      <p>Have a chat and know your roommate or renter better before you decide. Every member of UrCrib is a verified member.</p>
                  </div>
              </div>
              <div class="col-sm-4 text-center padding wow fadeIn" data-wow-duration="1000ms" data-wow-delay="900ms">
                  <div class="single-service">
                      <div class="wow scaleIn" data-wow-duration="500ms" data-wow-delay="900ms">
                          <%= image_tag "temp/icon3.png" %>
                      </div>
                      <h2>Moving Sale</h2>
                      <p>Post the items you feel are unwanted in your new crib for sale.</p>
                  </div>
              </div>
          </div>
      </div>
  </section>

  <section id="action">
      <div class="vertical-center">
           <div class="container">
              <div class="row">
                  <div class="action count">
                      <div class="col-sm-3 text-center wow bounceIn" data-wow-duration="1000ms" data-wow-delay="300ms">
                          <h1 class="timer bold" data-to="7000" data-speed="3000" data-from="0">700</h1>
                          <h3>Members</h3>
                      </div>
                      <div class="col-sm-3 text-center wow bounceIn" data-wow-duration="1000ms" data-wow-delay="300ms">
                          <h1 class="timer bold" data-to="12" data-speed="3000" data-from="0">1000</h1>
                          <h3>Cribs Posted</h3>
                      </div>
                      <div class="col-sm-3 text-center wow bounceIn" data-wow-duration="1000ms" data-wow-delay="300ms">
                          <h1 class="timer bold" data-to="432" data-speed="3000" data-from="0">600</h1>
                          <h3>Sale Items Posted</h3>
                      </div>
                      <div class="col-sm-3 text-center wow bounceIn" data-wow-duration="1000ms" data-wow-delay="300ms">
                          <h1 class="timer bold" data-to="145" data-speed="3000" data-from="0">11,000</h1>
                          <h3>Total Visitors</h3>
                      </div>
                  </div>
              </div>
          </div>
      </div>
 </section>

</body>
</html>